name: Rename File Extensions

on:
  push:
    paths:
      - 'assets/圖象/畫廊/**'

jobs:
  rename-extensions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rename file extensions
      run: |
        cd ${{ github.workspace }}/assets/圖象/畫廊/
        find . -type f | while read FILE ; do
          newfile="$(echo $FILE | sed 's/\(.*\)\.\([^.]*\)$/\1.\L\2/')" ;
          if [ "$FILE" != "$newfile" ]; then
            mv "$FILE" "$newfile" ;
          fi ;
        done
